# Import all the needed libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
journal = pd.read_csv('PSI Journals.csv')
journal.head()

Title  Citation Count  \
0                     Law, Innovation and Technology             106   
1  World Journal on Educational Technology: Curre...              11   
2                                           Machines             597   
3  Indonesian Journal of Electrical Engineering a...             215   
4    Karbala International Journal of Modern Science             499   

   Scholarly Output  Percent Cited  CiteScore   SNIP    SJR  \
0                43           55.8        2.5  1.839  0.492   
1                13           46.2        0.8    NaN    NaN   
2               188           67.6        3.2  1.237  0.421   
3               181           43.6        1.2  0.529  0.189   
4               139           64.7        3.6  1.270  0.334   

                       subject_area  Percentile  RANK  ...  Print ISSN  \
0  Computer Science (miscellaneous)        60.0  26.0  ...   1757-9961   
1  Computer Science (miscellaneous)        27.0  47.0  ...   1309-1506   
2  Computer Science (miscellaneous)        71.0  19.0  ...         NaN   
3  Computer Science (miscellaneous)        38.0  40.0  ...         NaN   
4  Computer Science (miscellaneous)        75.0  16.0  ...   2405-609X   

      E-ISSN   Index          Publisher2 Percentile2 Open Access2 user_index  \
0  1757-997X  Scopus  Taylor and Francis       200.0           No        1.0   
1  1309-0348  Scopus              Others       300.0          Yes        1.0   
2  2075-1702  Scopus              Others       200.0          Yes        1.0   
3  2089-3272  Scopus              Others       300.0           No        1.0   
4  2405-6103  Scopus              Others       100.0          Yes        1.0   

  user_publisher user_percentile  user_open_access  
0          0.625            0.75               0.5  
1          0.125            0.50               1.0  
2          0.125            0.75               1.0  
3          0.125            0.50               0.5  
4          0.125            1.00               1.0  

[5 rows x 25 columns]

In [3]:
journal.columns

Index(['Title', 'Citation Count', 'Scholarly Output', 'Percent Cited',
       'CiteScore', 'SNIP', 'SJR', 'subject_area', 'Percentile', 'RANK',
       'Rank Out Of', 'Publisher', 'Open Access', 'Quartile',
       'URL Scopus Source ID', 'Print ISSN', 'E-ISSN', 'Index', 'Publisher2',
       'Percentile2', 'Open Access2', 'user_index', 'user_publisher',
       'user_percentile', 'user_open_access'],
      dtype='object')

In [4]:
number = len(journal)
columns = journal.columns[21:25]

In [5]:
print(columns)

Index(['user_index', 'user_publisher', 'user_percentile', 'user_open_access'], dtype='object')


## Mean

In [6]:
#Mean - 4
mean = []
for i in columns:
    mean_criteria = np.mean(journal[i])
    mean.append(mean_criteria)
print(mean)
np.array(mean).round(4)

[0.9322033898305084, 0.2902542372881356, 0.6186440677966102, 0.6694915254237288]


array([0.9322, 0.2903, 0.6186, 0.6695])

## Variance

In [7]:
#Variance - 5
variance = []
for i in columns:
    variance_criteria = np.var(journal[i])*number
    variance.append(variance_criteria)
print(variance)
np.array(variance).round(4)

[1.728813559322035, 5.232521186440677, 4.66949152542373, 3.30508474576271]


array([1.7288, 5.2325, 4.6695, 3.3051])

## Deviation

In [8]:
#Deviation - 6
deviation = []
for (i, j) in zip(columns, variance):
    deviation_criteria = 1 - j
    deviation.append(deviation_criteria)
print(deviation)
np.array(deviation).round(4)

[-0.7288135593220351, -4.232521186440677, -3.66949152542373, -2.30508474576271]


array([-0.7288, -4.2325, -3.6695, -2.3051])

# Finding Overall preference value 

In [9]:
#Finding Overall preference value - 7
preference_value = []
overall = sum(deviation)
for (i, j) in zip(columns, deviation):
    preference_criteria = j/overall
    preference_value.append(preference_criteria)
print(preference_value)
sum_ = sum(preference_value)
np.array(preference_value).round(4)

[0.06664406451300442, 0.3870295926769022, 0.33554511551314975, 0.2107812272969437]


array([0.0666, 0.387 , 0.3355, 0.2108])

In [10]:
sum_

1.0

## Calculating PSI

In [11]:
#Calculating PSI - 8
for (i,j) in zip(columns, preference_value): 
    journal[i] = journal.loc[:, i] * j
    
psi_rank = journal.iloc[:, 21:25]
psi = []
for i in range(number):
    psi_sum = sum(psi_rank.loc[i])
    psi.append(psi_sum)
journal['PSI'] = psi

In [12]:
journal.head()

Title  Citation Count  \
0                     Law, Innovation and Technology             106   
1  World Journal on Educational Technology: Curre...              11   
2                                           Machines             597   
3  Indonesian Journal of Electrical Engineering a...             215   
4    Karbala International Journal of Modern Science             499   

   Scholarly Output  Percent Cited  CiteScore   SNIP    SJR  \
0                43           55.8        2.5  1.839  0.492   
1                13           46.2        0.8    NaN    NaN   
2               188           67.6        3.2  1.237  0.421   
3               181           43.6        1.2  0.529  0.189   
4               139           64.7        3.6  1.270  0.334   

                       subject_area  Percentile  RANK  ...     E-ISSN   Index  \
0  Computer Science (miscellaneous)        60.0  26.0  ...  1757-997X  Scopus   
1  Computer Science (miscellaneous)        27.0  47.0  ...  1309-0348  Scopus   
2  Computer Science (miscellaneous)        71.0  19.0  ...  2075-1702  Scopus   
3  Computer Science (miscellaneous)        38.0  40.0  ...  2089-3272  Scopus   
4  Computer Science (miscellaneous)        75.0  16.0  ...  2405-6103  Scopus   

           Publisher2  Percentile2 Open Access2 user_index user_publisher  \
0  Taylor and Francis        200.0           No   0.066644       0.241893   
1              Others        300.0          Yes   0.066644       0.048379   
2              Others        200.0          Yes   0.066644       0.048379   
3              Others        300.0           No   0.066644       0.048379   
4              Others        100.0          Yes   0.066644       0.048379   

  user_percentile user_open_access       PSI  
0        0.251659         0.105391  0.665587  
1        0.167773         0.210781  0.493577  
2        0.251659         0.210781  0.577463  
3        0.167773         0.105391  0.388186  
4        0.335545         0.210781  0.661349  

[5 rows x 26 columns]

In [13]:
ranked_journal = journal.sort_values('PSI', ascending=False)
ranked_journal.head()

Title  Citation Count  \
25                            npj Quantum Information            1996   
57          Software-Intensive Cyber-Physical Systems             480   
33  Journal of Computer Virology and Hacking Techn...             354   
43                                    Ocean Modelling            2525   
21       Journal of Reliable Intelligent Environments             196   

    Scholarly Output  Percent Cited  CiteScore   SNIP    SJR  \
25               223           78.5        9.0  2.424  4.098   
57               128           66.4        3.8  0.815  0.437   
33                87           78.2        4.1  1.474  0.439   
43               393           80.4        6.4  1.452  1.709   
21                62           74.2        3.2  1.093  0.441   

                        subject_area  Percentile  RANK  ...     E-ISSN  \
25  Computer Science (miscellaneous)        94.0   4.0  ...  2056-6387   
57  Computer Science (miscellaneous)        78.0  14.0  ...  2524-8529   
33  Computer Science (miscellaneous)        80.0  13.0  ...  2263-8733   
43  Computer Science (miscellaneous)        89.0   7.0  ...  1463-5011   
21  Computer Science (miscellaneous)        69.0  20.0  ...  2199-4676   

     Index Publisher2  Percentile2 Open Access2 user_index user_publisher  \
25  Scopus   Springer        100.0          Yes   0.066644       0.387030   
57  Scopus   Springer        100.0           No   0.066644       0.387030   
33  Scopus   Springer        100.0           No   0.066644       0.387030   
43  Scopus   Elsevier        100.0           No   0.066644       0.338651   
21  Scopus   Springer        200.0           No   0.066644       0.387030   

   user_percentile user_open_access       PSI  
25        0.335545         0.210781  1.000000  
57        0.335545         0.105391  0.894609  
33        0.335545         0.105391  0.894609  
43        0.335545         0.105391  0.846231  
21        0.251659         0.105391  0.810723  

[5 rows x 26 columns]

In [14]:
ranked_journal.to_csv('Result Journals.csv', index=False) 