# Import all the needed libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
journal = pd.read_csv('User Journals.csv')
journal.head()

scopus_source_id                                              title  \
0             13024                                   Acta Cybernetica   
1            144674                               Journal of Geomatics   
2            145095         Journal of Logic, Language and Information   
3             15591  Journal of Artificial Societies and Social Sim...   
4       17700155307  Chongqing Daxue Xuebao/Journal of Chongqing Un...   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
0       0.37          19              30                81             23   
1       0.10           6              41               413              7   
2       0.91          37              40                44             50   
3       2.42          79             404               167             69   
4       0.33          14             129               389             24   

    snip    sjr  rank  ...                                    journal_website  \
0  0.373  0.138    41  ...  http://www.inf.u-szeged.hu/actacybernetica/edb...   
1  0.074  0.111    47  ...  https://ores.su/en/journals/journal-of-geomatics/   
2  1.514  0.342    32  ...  http://www.springer.com/philosophy/logic+and+p...   
3  1.493  1.097    11  ...           http://jasss.soc.surrey.ac.uk/JASSS.html   
4  0.301  0.203    43  ...                                                NaN   

  review_time open_access2 print_issn     e_issn user_index user_publisher  \
0         NaN           No  0324-721X        NaN        1.0          0.143   
1         NaN           No  2095-6045        NaN        1.0          0.143   
2         NaN           No  0925-8531  1572-9583        1.0          1.000   
3    21 weeks          Yes  1460-7425        NaN        1.0          0.143   
4         NaN           No  1000-582X        NaN        1.0          0.143   

  user_percentile user_frequency user_open_access  
0            0.25          0.222              1.0  
1            0.25          0.556              1.0  
2            0.50          0.444              1.0  
3            1.00          0.444              0.5  
4            0.25          0.556              1.0  

[5 rows x 33 columns]

In [3]:
number = len(journal)
columns = journal.columns[28:33]

In [4]:
print(columns)

Index(['user_index', 'user_publisher', 'user_percentile', 'user_frequency',
       'user_open_access'],
      dtype='object')


## Mean

In [5]:
#Mean - 4
mean = []
for i in columns:
    mean_criteria = np.mean(journal[i])
    mean.append(mean_criteria)
print(mean)
np.array(mean).round(4)

[0.9326923076923077, 0.28307692307692317, 0.6538461538461539, 0.48090384615384646, 0.8557692307692307]


array([0.9327, 0.2831, 0.6538, 0.4809, 0.8558])

## Variance

In [6]:
#Variance - 5
variance = []
for i in columns:
    variance_criteria = np.var(journal[i])*number
    variance.append(variance_criteria)
print(variance)
np.array(variance).round(4)

[1.5144230769230769, 3.8135176923076943, 4.0192307692307665, 1.0335525192307697, 2.6682692307692326]


array([1.5144, 3.8135, 4.0192, 1.0336, 2.6683])

## Deviation

In [7]:
#Deviation - 6
deviation = []
for (i, j) in zip(columns, variance):
    deviation_criteria = 1 - j
    deviation.append(deviation_criteria)
print(deviation)
np.array(deviation).round(4)

[-0.5144230769230769, -2.8135176923076943, -3.0192307692307665, -0.03355251923076974, -1.6682692307692326]


array([-0.5144, -2.8135, -3.0192, -0.0336, -1.6683])

# Finding Overall preference value 

In [8]:
#Finding Overall preference value - 7
preference_value = []
overall = sum(deviation)
for (i, j) in zip(columns, deviation):
    preference_criteria = j/overall
    preference_value.append(preference_criteria)
print(preference_value)
sum_ = sum(preference_value)
np.array(preference_value).round(4)

[0.06391148041588218, 0.3495490170604256, 0.37510663272125216, 0.00416853611728913, 0.20726433368515088]


array([0.0639, 0.3495, 0.3751, 0.0042, 0.2073])

In [9]:
sum_

1.0

## Calculating PSI

In [10]:
#Calculating PSI - 8
for (i,j) in zip(columns, preference_value): 
    journal[i] = journal.loc[:, i] * j
    
psi_rank = journal.iloc[:, 28:33]
psi = []
for i in range(number):
    psi_sum = sum(psi_rank.loc[i])
    psi.append(psi_sum)
journal['PSI'] = psi

In [11]:
journal.head()

scopus_source_id                                              title  \
0             13024                                   Acta Cybernetica   
1            144674                               Journal of Geomatics   
2            145095         Journal of Logic, Language and Information   
3             15591  Journal of Artificial Societies and Social Sim...   
4       17700155307  Chongqing Daxue Xuebao/Journal of Chongqing Un...   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
0       0.37          19              30                81             23   
1       0.10           6              41               413              7   
2       0.91          37              40                44             50   
3       2.42          79             404               167             69   
4       0.33          14             129               389             24   

    snip    sjr  rank  ...  review_time open_access2 print_issn     e_issn  \
0  0.373  0.138    41  ...          NaN           No  0324-721X        NaN   
1  0.074  0.111    47  ...          NaN           No  2095-6045        NaN   
2  1.514  0.342    32  ...          NaN           No  0925-8531  1572-9583   
3  1.493  1.097    11  ...     21 weeks          Yes  1460-7425        NaN   
4  0.301  0.203    43  ...          NaN           No  1000-582X        NaN   

   user_index user_publisher user_percentile user_frequency user_open_access  \
0    0.063911       0.049986        0.093777       0.000925         0.207264   
1    0.063911       0.049986        0.093777       0.002318         0.207264   
2    0.063911       0.349549        0.187553       0.001851         0.207264   
3    0.063911       0.049986        0.375107       0.001851         0.103632   
4    0.063911       0.049986        0.093777       0.002318         0.207264   

        PSI  
0  0.415863  
1  0.417256  
2  0.810129  
3  0.594487  
4  0.417256  

[5 rows x 34 columns]

In [12]:
ranked_journal = journal.sort_values('PSI', ascending=False)
ranked_journal.head()

scopus_source_id                                              title  \
35             28352                                    Ocean Modelling   
17       21100405702  Journal of Computer Virology and Hacking Techn...   
14       21100368801  IEEE/ACM Transactions on Audio Speech and Lang...   
13       21100338508  IEEE Transactions on Emerging Topics in Computing   
47       21100338508  IEEE Transactions on Emerging Topics in Computing   

    citescore  percentile  citation_count  scholarly_output  percent_cited  \
35       3.27          87            1093               334             82   
17       1.84          67             138                75             53   
14       5.06          95            2388               472             85   
13       4.36          91             659               151             74   
47       4.36          91             659               151             74   

     snip    sjr  rank  ...  review_time open_access2 print_issn     e_issn  \
35  1.392  1.899     7  ...          NaN           No  1463-5003  1463-5011   
17  1.100  0.279    17  ...          NaN           No        NaN  2263-8733   
14  2.382  1.045     3  ...          NaN           No  2329-9290  2329-9304   
13  1.830  0.659     5  ...          NaN           No  2168-6750        NaN   
47  1.830  0.659     5  ...          NaN           No  2168-6750        NaN   

    user_index user_publisher user_percentile user_frequency user_open_access  \
35    0.063911       0.299564        0.375107       0.002780         0.207264   
17    0.063911       0.349549        0.281330       0.002318         0.207264   
14    0.063911       0.249578        0.375107       0.002780         0.207264   
13    0.063911       0.249578        0.375107       0.001851         0.207264   
47    0.031956       0.249578        0.375107       0.001851         0.207264   

         PSI  
35  0.948626  
17  0.904373  
14  0.898641  
13  0.897711  
47  0.865756  

[5 rows x 34 columns]

In [13]:
ranked_journal.to_csv('Result Journals.csv', index=False) 