# Import all the needed libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
journal = pd.read_csv('User Journals.csv')
journal.head()

scopus_source_id                                              title  \
0             13024                                   Acta Cybernetica   
1            144674                               Journal of Geomatics   
2            145095         Journal of Logic, Language and Information   
3             15591  Journal of Artificial Societies and Social Sim...   
4       17700155307  Chongqing Daxue Xuebao/Journal of Chongqing Un...   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
0       0.37          19              30                81             23   
1       0.10           6              41               413              7   
2       0.91          37              40                44             50   
3       2.42          79             404               167             69   
4       0.33          14             129               389             24   

    snip    sjr  rank  ...                                    journal_website  \
0  0.373  0.138    41  ...  http://www.inf.u-szeged.hu/actacybernetica/edb...   
1  0.074  0.111    47  ...  https://ores.su/en/journals/journal-of-geomatics/   
2  1.514  0.342    32  ...  http://www.springer.com/philosophy/logic+and+p...   
3  1.493  1.097    11  ...           http://jasss.soc.surrey.ac.uk/JASSS.html   
4  0.301  0.203    43  ...                                                NaN   

  review_time open_access2 print_issn     e_issn user_index user_publisher  \
0         NaN           No  0324-721X        NaN        0.5          1.000   
1         NaN           No  2095-6045        NaN        0.5          1.000   
2         NaN           No  0925-8531  1572-9583        0.5          0.143   
3    21 weeks          Yes  1460-7425        NaN        0.5          1.000   
4         NaN           No  1000-582X        NaN        0.5          1.000   

  user_percentile user_frequency user_open_access  
0            1.00          0.875              1.0  
1            1.00          0.500              1.0  
2            0.75          0.625              1.0  
3            0.25          0.625              0.5  
4            1.00          0.500              1.0  

[5 rows x 33 columns]

In [3]:
number = len(journal)
columns = journal.columns[28:33]

In [4]:
print(columns)

Index(['user_index', 'user_publisher', 'user_percentile', 'user_frequency',
       'user_open_access'],
      dtype='object')


## Mean

In [5]:
#Mean - 4
mean = []
for i in columns:
    mean_criteria = np.mean(journal[i])
    mean.append(mean_criteria)
print(mean)
np.array(mean).round(4)

[0.5673076923076923, 0.8599038461538462, 0.5961538461538461, 0.5841346153846154, 0.8557692307692307]


array([0.5673, 0.8599, 0.5962, 0.5841, 0.8558])

## Variance

In [6]:
#Variance - 5
variance = []
for i in columns:
    variance_criteria = np.var(journal[i])*number
    variance.append(variance_criteria)
print(variance)
np.array(variance).round(4)

[1.5144230769230769, 3.8140945192307685, 4.0192307692307665, 1.3037860576923077, 2.6682692307692326]


array([1.5144, 3.8141, 4.0192, 1.3038, 2.6683])

## Deviation

In [7]:
#Deviation - 6
deviation = []
for (i, j) in zip(columns, variance):
    deviation_criteria = 1 - j
    deviation.append(deviation_criteria)
print(deviation)
np.array(deviation).round(4)

[-0.5144230769230769, -2.8140945192307685, -3.0192307692307665, -0.3037860576923077, -1.6682692307692326]


array([-0.5144, -2.8141, -3.0192, -0.3038, -1.6683])

# Finding Overall preference value 

In [8]:
#Finding Overall preference value - 7
preference_value = []
overall = sum(deviation)
for (i, j) in zip(columns, deviation):
    preference_criteria = j/overall
    preference_value.append(preference_criteria)
print(preference_value)
sum_ = sum(preference_value)
np.array(preference_value).round(4)

[0.061831155917395346, 0.3382404965686714, 0.3628968777207874, 0.036513609014302985, 0.2005178607788431]


array([0.0618, 0.3382, 0.3629, 0.0365, 0.2005])

In [9]:
sum_

1.0000000000000002

## Calculating PSI

In [10]:
#Calculating PSI - 8
for (i,j) in zip(columns, preference_value): 
    journal[i] = journal.loc[:, i] * j
    
psi_rank = journal.iloc[:, 28:33]
psi = []
for i in range(number):
    psi_sum = sum(psi_rank.loc[i])
    psi.append(psi_sum)
journal['PSI'] = psi

In [11]:
journal.head()

scopus_source_id                                              title  \
0             13024                                   Acta Cybernetica   
1            144674                               Journal of Geomatics   
2            145095         Journal of Logic, Language and Information   
3             15591  Journal of Artificial Societies and Social Sim...   
4       17700155307  Chongqing Daxue Xuebao/Journal of Chongqing Un...   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
0       0.37          19              30                81             23   
1       0.10           6              41               413              7   
2       0.91          37              40                44             50   
3       2.42          79             404               167             69   
4       0.33          14             129               389             24   

    snip    sjr  rank  ...  review_time open_access2 print_issn     e_issn  \
0  0.373  0.138    41  ...          NaN           No  0324-721X        NaN   
1  0.074  0.111    47  ...          NaN           No  2095-6045        NaN   
2  1.514  0.342    32  ...          NaN           No  0925-8531  1572-9583   
3  1.493  1.097    11  ...     21 weeks          Yes  1460-7425        NaN   
4  0.301  0.203    43  ...          NaN           No  1000-582X        NaN   

   user_index user_publisher user_percentile user_frequency user_open_access  \
0    0.030916       0.338240        0.362897       0.031949         0.200518   
1    0.030916       0.338240        0.362897       0.018257         0.200518   
2    0.030916       0.048368        0.272173       0.022821         0.200518   
3    0.030916       0.338240        0.090724       0.022821         0.100259   
4    0.030916       0.338240        0.362897       0.018257         0.200518   

        PSI  
0  0.964520  
1  0.950828  
2  0.574795  
3  0.582960  
4  0.950828  

[5 rows x 34 columns]

In [12]:
ranked_journal = journal.sort_values('PSI', ascending=False)
ranked_journal.head()

scopus_source_id                                              title  \
0              13024                                   Acta Cybernetica   
31       21100854726  International Journal of Mathematics and Compu...   
37        4700152467  Shenzhen Daxue Xuebao (Ligong Ban)/Journal of ...   
1             144674                               Journal of Geomatics   
29       21100842538                                       Jusletter IT   

    citescore  percentile  citation_count  scholarly_output  percent_cited  \
0        0.37          19              30                81             23   
31       0.44          23               4                 9             44   
37       0.24          10              65               268             19   
1        0.10           6              41               413              7   
29       0.01           1               1               123              1   

     snip    sjr  rank  ...  review_time open_access2 print_issn     e_issn  \
0   0.373  0.138    41  ...          NaN           No  0324-721X        NaN   
31  0.775  0.103    39  ...          NaN           No  1814-0424  1814-0432   
37  0.215  0.148    45  ...          NaN           No  1000-2618        NaN   
1   0.074  0.111    47  ...          NaN           No  2095-6045        NaN   
29  0.018  0.100    50  ...          NaN           No        NaN  1664-848X   

    user_index user_publisher user_percentile user_frequency user_open_access  \
0     0.030916        0.33824        0.362897       0.031949         0.200518   
31    0.030916        0.33824        0.362897       0.031949         0.200518   
37    0.030916        0.33824        0.362897       0.018257         0.200518   
1     0.030916        0.33824        0.362897       0.018257         0.200518   
29    0.030916        0.33824        0.362897       0.018257         0.200518   

         PSI  
0   0.964520  
31  0.964520  
37  0.950828  
1   0.950828  
29  0.950828  

[5 rows x 34 columns]

In [13]:
ranked_journal.to_csv('Result Journals.csv', index=False) 