# Import all the needed libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
journal = pd.read_csv('User Journals.csv')
journal.head()

scopus_source_id                                             title  \
0             18902  IEEE Journal on Selected Areas in Communications   
1             15773           ACM Transactions on Internet Technology   
2             12373           Journal of Computer Information Systems   
3       21100358105   IEEE Transactions on Control of Network Systems   
4             26811                                 Computer Networks   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
0      10.91          98            8074               740             92   
1       3.33          80             320                96             76   
2       2.46          72             273               111             76   
3       5.80          91             911               157             82   
4       4.19          84            3778               901             77   

    snip    sjr  rank  ...                                    journal_website  \
0  3.311  2.294     5  ...  http://ieeexplore.ieee.org/xpl/aboutJournal.js...   
1  1.771  0.538    53  ...                               http://toit.acm.org/   
2  1.023  0.685    75  ...              http://www.tandfonline.com/loi/ucis20   
3  2.241  2.098    23  ...  http://ieeexplore.ieee.org/servlet/opac?punumb...   
4  1.600  0.592    42  ...  http://www.journals.elsevier.com/computer-netw...   

  review_time open_access2 print_issn     e_issn user_index user_publisher  \
0         NaN           No  0733-8716  1558-0008        1.0          0.714   
1         NaN           No  1533-5399  1557-6051        1.0          0.286   
2         NaN           No  0887-4417  2380-2057        1.0          0.571   
3         NaN           No  2325-5870  2372-2533        0.5          0.714   
4         NaN           No  1389-1286  1872-7069        1.0          1.000   

  user_percentile user_frequency user_open_access  
0            1.00          0.667              1.0  
1            1.00          0.444              1.0  
2            0.75          0.444              1.0  
3            1.00          0.444              1.0  
4            1.00          0.778              1.0  

[5 rows x 33 columns]

In [3]:
number = len(journal)
columns = journal.columns[28:33]

In [4]:
print(columns)

Index(['user_index', 'user_publisher', 'user_percentile', 'user_frequency',
       'user_open_access'],
      dtype='object')


## Mean

In [5]:
#Mean - 4
mean = []
for i in columns:
    mean_criteria = np.mean(journal[i])
    mean.append(mean_criteria)
print(mean)
np.array(mean).round(4)

[0.9166666666666666, 0.6903333333333334, 0.9583333333333334, 0.5368333333333334, 1.0]


array([0.9167, 0.6903, 0.9583, 0.5368, 1.    ])

## Variance

In [6]:
#Variance - 5
variance = []
for i in columns:
    variance_criteria = np.var(journal[i])*number
    variance.append(variance_criteria)
print(variance)
np.array(variance).round(4)

[0.20833333333333331, 0.30251733333333336, 0.05208333333333333, 0.10957683333333336, 0.0]


array([0.2083, 0.3025, 0.0521, 0.1096, 0.    ])

## Deviation

In [7]:
#Deviation - 6
deviation = []
for (i, j) in zip(columns, variance):
    deviation_criteria = 1 - j
    deviation.append(deviation_criteria)
print(deviation)
np.array(deviation).round(4)

[0.7916666666666667, 0.6974826666666667, 0.9479166666666666, 0.8904231666666667, 1.0]


array([0.7917, 0.6975, 0.9479, 0.8904, 1.    ])

# Finding Overall preference value 

In [8]:
#Finding Overall preference value - 7
preference_value = []
overall = sum(deviation)
for (i, j) in zip(columns, deviation):
    preference_criteria = j/overall
    preference_value.append(preference_criteria)
print(preference_value)
sum_ = sum(preference_value)
np.array(preference_value).round(4)

[0.1829390291175387, 0.16117490762060446, 0.2190454164433687, 0.20575976793317602, 0.23108087888531204]


array([0.1829, 0.1612, 0.219 , 0.2058, 0.2311])

In [9]:
sum_

1.0

## Calculating PSI

In [10]:
#Calculating PSI - 8
for (i,j) in zip(columns, preference_value): 
    journal[i] = journal.loc[:, i] * j
    
psi_rank = journal.iloc[:, 28:33]
psi = []
for i in range(number):
    psi_sum = sum(psi_rank.loc[i])
    psi.append(psi_sum)
journal['PSI'] = psi

In [11]:
journal.head()

scopus_source_id                                             title  \
0             18902  IEEE Journal on Selected Areas in Communications   
1             15773           ACM Transactions on Internet Technology   
2             12373           Journal of Computer Information Systems   
3       21100358105   IEEE Transactions on Control of Network Systems   
4             26811                                 Computer Networks   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
0      10.91          98            8074               740             92   
1       3.33          80             320                96             76   
2       2.46          72             273               111             76   
3       5.80          91             911               157             82   
4       4.19          84            3778               901             77   

    snip    sjr  rank  ...  review_time open_access2 print_issn     e_issn  \
0  3.311  2.294     5  ...          NaN           No  0733-8716  1558-0008   
1  1.771  0.538    53  ...          NaN           No  1533-5399  1557-6051   
2  1.023  0.685    75  ...          NaN           No  0887-4417  2380-2057   
3  2.241  2.098    23  ...          NaN           No  2325-5870  2372-2533   
4  1.600  0.592    42  ...          NaN           No  1389-1286  1872-7069   

   user_index user_publisher user_percentile user_frequency user_open_access  \
0    0.182939       0.115079        0.219045       0.137242         0.231081   
1    0.182939       0.046096        0.219045       0.091357         0.231081   
2    0.182939       0.092031        0.164284       0.091357         0.231081   
3    0.091470       0.115079        0.219045       0.091357         0.231081   
4    0.182939       0.161175        0.219045       0.160081         0.231081   

        PSI  
0  0.885386  
1  0.770519  
2  0.761692  
3  0.748032  
4  0.954321  

[5 rows x 34 columns]

In [12]:
ranked_journal = journal.sort_values('PSI', ascending=False)
ranked_journal.head()

scopus_source_id                                             title  \
4             26811                                 Computer Networks   
0             18902  IEEE Journal on Selected Areas in Communications   
5             27287         Journal of Network and Systems Management   
1             15773           ACM Transactions on Internet Technology   
2             12373           Journal of Computer Information Systems   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
4       4.19          84            3778               901             77   
0      10.91          98            8074               740             92   
5       2.60          75             273               105             60   
1       3.33          80             320                96             76   
2       2.46          72             273               111             76   

    snip    sjr  rank  ...  review_time open_access2 print_issn     e_issn  \
4  1.600  0.592    42  ...          NaN           No  1389-1286  1872-7069   
0  3.311  2.294     5  ...          NaN           No  0733-8716  1558-0008   
5  1.224  0.386    66  ...          NaN           No  1064-7570  1573-7705   
1  1.771  0.538    53  ...          NaN           No  1533-5399  1557-6051   
2  1.023  0.685    75  ...          NaN           No  0887-4417  2380-2057   

   user_index user_publisher user_percentile user_frequency user_open_access  \
4    0.182939       0.161175        0.219045       0.160081         0.231081   
0    0.182939       0.115079        0.219045       0.137242         0.231081   
5    0.182939       0.138127        0.219045       0.091357         0.231081   
1    0.182939       0.046096        0.219045       0.091357         0.231081   
2    0.182939       0.092031        0.164284       0.091357         0.231081   

        PSI  
4  0.954321  
0  0.885386  
5  0.862550  
1  0.770519  
2  0.761692  

[5 rows x 34 columns]

In [13]:
ranked_journal.to_csv('Result Journals.csv', index=False) 