# Import all the needed libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
journal = pd.read_csv('User Journals.csv')
journal.head()

scopus_source_id                                              title  \
0             24800                  Neural Computing and Applications   
1             24357  Journal of Experimental and Theoretical Artifi...   
2             24201                   Expert Systems with Applications   
3       21100235616  IEEE Transactions on Neural Networks and Learn...   
4             24330        Journal of Artificial Intelligence Research   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
0       4.20          82            3124               744             80   
1       2.20          63             383               174             56   
2       6.36          92           13082              2056             91   
3      12.16          97            9306               765             94   
4       3.23          73             585               181             76   

    snip    sjr  rank  ...                                    journal_website  \
0  1.481  0.637    34  ...        http://www.springerlink.com/content/102827/   
1  0.999  0.392    70  ...              http://www.tandfonline.com/loi/teta20   
2  2.696  1.190    14  ...  http://www.elsevier.com/wps/find/journaldescri...   
3  4.062  3.658     5  ...  http://ieeexplore.ieee.org/xpl/aboutJournal.js...   
4  2.084  0.754    51  ...                               http://www.jair.org/   

  review_time open_access2 print_issn     e_issn user_index user_publisher  \
0         NaN           No  0941-0643  1433-3058        1.0          0.714   
1         NaN           No  0952-813X  1362-3079        1.0          0.857   
2         NaN           No  0957-4174  1873-6793        1.0          1.000   
3         NaN           No  2162-237X  2162-2388        1.0          0.429   
4    27 weeks          Yes  1076-9757  1943-5037        0.5          0.143   

  user_percentile user_frequency user_open_access  
0            0.75          0.667              1.0  
1            1.00          1.000              1.0  
2            0.75          0.556              1.0  
3            0.75          0.667              1.0  
4            1.00          0.111              0.5  

[5 rows x 33 columns]

In [3]:
number = len(journal)
columns = journal.columns[28:33]

In [4]:
print(columns)

Index(['user_index', 'user_publisher', 'user_percentile', 'user_frequency',
       'user_open_access'],
      dtype='object')


## Mean

In [5]:
#Mean - 4
mean = []
for i in columns:
    mean_criteria = np.mean(journal[i])
    mean.append(mean_criteria)
print(mean)
np.array(mean).round(4)

[0.9166666666666666, 0.5715, 0.8333333333333334, 0.6298333333333334, 0.9166666666666666]


array([0.9167, 0.5715, 0.8333, 0.6298, 0.9167])

## Variance

In [6]:
#Variance - 5
variance = []
for i in columns:
    variance_criteria = np.var(journal[i])*number
    variance.append(variance_criteria)
print(variance)
np.array(variance).round(4)

[0.20833333333333334, 0.5708575, 0.08333333333333333, 0.4363788333333334, 0.20833333333333334]


array([0.2083, 0.5709, 0.0833, 0.4364, 0.2083])

## Deviation

In [7]:
#Deviation - 6
deviation = []
for (i, j) in zip(columns, variance):
    deviation_criteria = 1 - j
    deviation.append(deviation_criteria)
print(deviation)
np.array(deviation).round(4)

[0.7916666666666666, 0.4291425, 0.9166666666666666, 0.5636211666666666, 0.7916666666666666]


array([0.7917, 0.4291, 0.9167, 0.5636, 0.7917])

# Finding Overall preference value 

In [8]:
#Finding Overall preference value - 7
preference_value = []
overall = sum(deviation)
for (i, j) in zip(columns, deviation):
    preference_criteria = j/overall
    preference_value.append(preference_criteria)
print(preference_value)
sum_ = sum(preference_value)
np.array(preference_value).round(4)

[0.2266590992748722, 0.12286617159229497, 0.26244737810774676, 0.16136825175021385, 0.2266590992748722]


array([0.2267, 0.1229, 0.2624, 0.1614, 0.2267])

In [9]:
sum_

1.0

## Calculating PSI

In [10]:
#Calculating PSI - 8
for (i,j) in zip(columns, preference_value): 
    journal[i] = journal.loc[:, i] * j
    
psi_rank = journal.iloc[:, 28:33]
psi = []
for i in range(number):
    psi_sum = sum(psi_rank.loc[i])
    psi.append(psi_sum)
journal['PSI'] = psi

In [11]:
journal.head(6)

scopus_source_id                                              title  \
0             24800                  Neural Computing and Applications   
1             24357  Journal of Experimental and Theoretical Artifi...   
2             24201                   Expert Systems with Applications   
3       21100235616  IEEE Transactions on Neural Networks and Learn...   
4             24330        Journal of Artificial Intelligence Research   
5       19700190323  ACM Transactions on Intelligent Systems and Te...   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
0       4.20          82            3124               744             80   
1       2.20          63             383               174             56   
2       6.36          92           13082              2056             91   
3      12.16          97            9306               765             94   
4       3.23          73             585               181             76   
5       4.40          86            1073               244             74   

    snip    sjr  rank  ...  review_time open_access2 print_issn     e_issn  \
0  1.481  0.637    34  ...          NaN           No  0941-0643  1433-3058   
1  0.999  0.392    70  ...          NaN           No  0952-813X  1362-3079   
2  2.696  1.190    14  ...          NaN           No  0957-4174  1873-6793   
3  4.062  3.658     5  ...          NaN           No  2162-237X  2162-2388   
4  2.084  0.754    51  ...     27 weeks          Yes  1076-9757  1943-5037   
5  2.177  0.708    27  ...          NaN           No  2157-6904  2157-6912   

   user_index user_publisher user_percentile user_frequency user_open_access  \
0    0.226659       0.087726        0.196836       0.107633         0.226659   
1    0.226659       0.105296        0.262447       0.161368         0.226659   
2    0.226659       0.122866        0.196836       0.089721         0.226659   
3    0.226659       0.052710        0.196836       0.107633         0.226659   
4    0.113330       0.017570        0.262447       0.017912         0.113330   
5    0.226659       0.035140        0.196836       0.125544         0.226659   

        PSI  
0  0.845513  
1  0.982430  
2  0.862741  
3  0.810496  
4  0.524588  
5  0.810838  

[6 rows x 34 columns]

In [12]:
ranked_journal = journal.sort_values('PSI', ascending=False)
ranked_journal.head(6)

scopus_source_id                                              title  \
1             24357  Journal of Experimental and Theoretical Artifi...   
2             24201                   Expert Systems with Applications   
0             24800                  Neural Computing and Applications   
5       19700190323  ACM Transactions on Intelligent Systems and Te...   
3       21100235616  IEEE Transactions on Neural Networks and Learn...   
4             24330        Journal of Artificial Intelligence Research   

   citescore  percentile  citation_count  scholarly_output  percent_cited  \
1       2.20          63             383               174             56   
2       6.36          92           13082              2056             91   
0       4.20          82            3124               744             80   
5       4.40          86            1073               244             74   
3      12.16          97            9306               765             94   
4       3.23          73             585               181             76   

    snip    sjr  rank  ...  review_time open_access2 print_issn     e_issn  \
1  0.999  0.392    70  ...          NaN           No  0952-813X  1362-3079   
2  2.696  1.190    14  ...          NaN           No  0957-4174  1873-6793   
0  1.481  0.637    34  ...          NaN           No  0941-0643  1433-3058   
5  2.177  0.708    27  ...          NaN           No  2157-6904  2157-6912   
3  4.062  3.658     5  ...          NaN           No  2162-237X  2162-2388   
4  2.084  0.754    51  ...     27 weeks          Yes  1076-9757  1943-5037   

   user_index user_publisher user_percentile user_frequency user_open_access  \
1    0.226659       0.105296        0.262447       0.161368         0.226659   
2    0.226659       0.122866        0.196836       0.089721         0.226659   
0    0.226659       0.087726        0.196836       0.107633         0.226659   
5    0.226659       0.035140        0.196836       0.125544         0.226659   
3    0.226659       0.052710        0.196836       0.107633         0.226659   
4    0.113330       0.017570        0.262447       0.017912         0.113330   

        PSI  
1  0.982430  
2  0.862741  
0  0.845513  
5  0.810838  
3  0.810496  
4  0.524588  

[6 rows x 34 columns]

In [13]:
ranked_journal.to_csv('Result Journals.csv', index=False) 